name: Java CI with Maven

# SUPUESTO 1: CONFIGURACIÓN DEL DISPARADOR
# En la imagen del profesor pone: branches: [ "main" ]
# Para el ejercicio quitamos esa línea para que funcione en TODAS las ramas.
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #Descargar el código
    - uses: actions/checkout@v4

    #Configurar Java 
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    #Compilar
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests