name: Supuesto 7

on: 
  push:

jobs:
  build: 
    #LA MATRIZ
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    #CAMBIAMOS ESTO para que use la variable de la matriz
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -DskipTests
      
	  #informe de zip
    - name: Subir informes de tests (Surefire)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        #Le a√±adimos el nombre del SO al archivo para que no se sobreescriban
        name: surefire-reports-${{ matrix.os }}
        path: target/surefire-reports/