name: Supuesto 6

on: 
  push:
    branches: ["feature-dev"]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    #Descargar el c√≥digo
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    #Le quitamos el skipTests
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
      
    #Evidencias de desastre
    - name: Subir informes de tests (Surefire)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: target/surefire-reports/