name: CD_Supuesto 3

# Se activa solo cuando se sube un tag que empiece por "v"
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Necesario para crear la Release en GitHub

    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Generar .war con Maven
        run: mvn -B clean package -DskipTests

      # Crea la Release oficial en GitHub y adjunta el .war como binario descargable
      - name: Crear Release oficial en GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.war
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}