name: Java CI with Maven


on: 
  push:
    branches: ["feature-dev"]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    #Descargar el c√≥digo
    - uses: actions/checkout@v4

    #Configurar Java 
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    #Compilar
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests