name: CD_Supuesto 7

# Se activa cuando otro workflow llamado "CI - Tests" termina
# Si el CI falló, este workflow no empieza
on:
  workflow_run:
    workflows: ["CI - Tests"]   # Debe coincidir exactamente con el name: del workflow de CI
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Condición: solo continúa si el workflow de CI terminó con éxito
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Generar .war con Maven
        run: mvn -B clean package -DskipTests

      - name: Subir .war como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-ejecutable
          path: target/*.war

      - name: Notificacion de despliegue exitoso
        run: echo "✅ CI pasó correctamente. Despliegue realizado por ${{ github.actor }}"